<a href="https://colab.research.google.com/github/darreneasler/MiniProject02/blob/main/MiniProject2.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
#1 Load and Inspect the Data (Loading Data)

import numpy as np
import matplotlib as plt
import pandas as pd
import gdown
print("pandas", pd.__version__)
print()
print("numpy", np.__version__)
print()
print("matplotlib", plt.__version__)
print()

csv_id = "1a-9znIQRtfbcEQnPLT957bGmBZL5bNew"
url = f"https://drive.google.com/uc?id={csv_id}"
gdown.download(url, "telco.csv", quiet=False)

print()
dataset = pd.read_csv("telco.csv")
print(dataset.shape)
print()
dataset.head()

pandas 2.2.2

numpy 2.0.2

matplotlib 3.10.0

Downloading...
From: https://drive.google.com/uc?id=1a-9znIQRtfbcEQnPLT957bGmBZL5bNew
To: /content/telco.csv
100%|██████████| 410k/410k [00:00<00:00, 35.8MB/s]

(7043, 24)

,gender,SeniorCitizen,Partner,Dependents,tenure,PhoneService,MultipleLines,OnlineSecurity,OnlineBackup,DeviceProtection,...,target,TotalCharges,Churn,InternetService_Fiber optic,InternetService_No,Contract_One year,Contract_Two year,PaymentMethod_Credit card (automatic),PaymentMethod_Electronic check,PaymentMethod_Mailed check
0,0,0,1,0,1,0,0,0,1,0,...,29.85,29.85,0,0,0,0,0,0,1,0
1,1,0,0,0,34,1,0,1,0,1,...,56.95,1889.5,0,0,0,1,0,0,0,1
2,1,0,0,0,2,1,0,1,1,0,...,53.85,108.15,1,0,0,0,0,0,0,1
3,1,0,0,0,45,0,0,1,0,1,...,42.30,1840.75,0,0,0,1,0,0,0,0
4,0,0,0,0,2,1,0,0,0,0,...,70.70,151.65,1,1,0,0,0,0,1,0

In [ ]:
#1 Load and Inspect the Data (Verify Data)

print(dataset.isnull().sum())
print()
print(f"Target (Monthly Charges) is type: {dataset['target'].dtypes}")

dataset = dataset.rename(columns = {"InternetService_Fiber optic": "InternetService_FO"})

gender                                   0
SeniorCitizen                            0
Partner                                  0
Dependents                               0
tenure                                   0
PhoneService                             0
MultipleLines                            0
OnlineSecurity                           0
OnlineBackup                             0
DeviceProtection                         0
TechSupport                              0
StreamingTV                              0
StreamingMovies                          0
PaperlessBilling                         0
target                                   0
TotalCharges                             0
Churn                                    0
InternetService_Fiber optic              0
InternetService_No                       0
Contract_One year                        0
Contract_Two year                        0
PaymentMethod_Credit card (automatic)    0
PaymentMethod_Electronic check           0
PaymentMethod_Mailed check               0
dtype: int64

Target (Monthly Charges) is type: float64

In [ ]:
#2 Define the Variables (Setting Target and Predictors)

dataset = dataset.rename(columns = {"target": "monthly_charges"})

predictors = ["PhoneService", "MultipleLines", "OnlineSecurity", "OnlineBackup", "DeviceProtection", "TechSupport", "StreamingTV", "StreamingMovies", "InternetService_FO", "InternetService_No"]
target = ["monthly_charges"]
delete_columns = dataset.columns.difference(predictors + target)

dataset = dataset.drop(columns = delete_columns)
dataset = dataset[["PhoneService", "MultipleLines", "OnlineSecurity", "OnlineBackup", "DeviceProtection", "TechSupport", "StreamingTV", "StreamingMovies", "InternetService_FO", "InternetService_No", "monthly_charges"]]
dataset = dataset.rename(columns = {"PhoneService": "phone_service", "MultipleLines": "multiple_lines", "OnlineSecurity": "online_security", "OnlineBackup": "online_backup", "DeviceProtection": "device_protection", "TechSupport": "tech_support", "StreamingTV": "streaming_tv", "StreamingMovies": "streaming_movies", "InternetService_FO": "internet_fo", "InternetService_No": "internet_no"})
print(dataset.head())
print()

   phone_service  multiple_lines  online_security  online_backup  \
0              0               0                0              1
1              1               0                1              0
2              1               0                1              1
3              0               0                1              0
4              1               0                0              0

   device_protection  tech_support  streaming_tv  streaming_movies  \
0                  0             0             0                 0
1                  1             0             0                 0
2                  0             0             0                 0
3                  1             1             0                 0
4                  0             0             0                 0

   internet_fo  internet_no  monthly_charges
0            0            0            29.85
1            0            0            56.95
2            0            0            53.85
3            0            0            42.30
4            1            0            70.70

In [ ]:
#3 Split the Data (Random Split 85/15)
from sklearn.model_selection import train_test_split

predictors = ['phone_service', 'multiple_lines', 'online_security', 'online_backup', 'device_protection', 'tech_support', 'streaming_tv', 'streaming_movies', 'internet_fo', 'internet_no']
target = ['monthly_charges']

X = dataset[predictors]
Y = dataset[target]
X_train, X_test, Y_train, Y_test = train_test_split(X, Y, test_size = 0.15, random_state = 42)

print("X_train shape:", X_train.shape)
print("X_test shape:", X_test.shape)
print("Y_train shape:", Y_train.shape)
print("Y_test shape:", Y_test.shape)

X_train shape: (5986, 10)
X_test shape: (1057, 10)
Y_train shape: (5986, 1)
Y_test shape: (1057, 1)

In [ ]:
#4 Fit a Multivariable Linear Regression (Y = w_0 + sum(w_i*X_i))

from sklearn import linear_model

model = linear_model.LinearRegression()
model.fit(X_train,Y_train)

LinearRegression()

In [ ]:
#5 Report the Parameters (Intercept and 10 Linear Coefficients)

intercept = float(model.intercept_)
print(f"Base Rate (Intercept): ${intercept:.2f} / mo")
print()

linear_coefficients = (pd.DataFrame({'service': predictors, '$': model.coef_[0]}).sort_values('$', ascending=False))
linear_coefficients

Base Rate (Intercept): $24.95 / mo

/tmp/ipykernel_5058/2135358835.py:3: DeprecationWarning: Conversion of an array with ndim > 0 to a scalar is deprecated, and will error in future. Ensure you extract a single element from your array before performing this operation. (Deprecated NumPy 1.25.)
  intercept = float(model.intercept_)

             service          $
8        internet_fo  24.943921
0      phone_service  20.049960
6       streaming_tv   9.978447
7   streaming_movies   9.947466
2    online_security   5.047718
1     multiple_lines   5.023497
5       tech_support   5.017040
4  device_protection   5.014711
3      online_backup   4.990427
9        internet_no -25.055467

In [ ]:
#6 Evaluate on the Test Set (Model Verification)

from sklearn.metrics import r2_score

Y_prediction = model.predict(X_test)

results = X_test.copy()
results = results.drop(columns = predictors)
results['actual'] = Y_test.values
results['model_prediction'] = Y_prediction
results['error'] = abs((results['actual'] - results['model_prediction']))
results['error_squared'] = results['error']**2
print(results.round(2).head(15))
print()

mae = (1/len(Y_test)) * results['error'].sum()
rmse = np.sqrt((1/len(Y_test)) * results['error_squared'].sum())
r_2 = r2_score(Y_test, Y_prediction)
print(f"Mean absolute error: {mae:.2f}")
print()
print(f"Root mean square error: {rmse:.2f}")
print()
print(f"R-Squared: {r_2:.5f}")

      actual  model_prediction  error  error_squared
185    24.80             24.95   0.15           0.02
2715   25.25             24.97   0.28           0.08
3825   19.35             19.95   0.60           0.36
1807   76.35             74.96   1.39           1.93
132    50.55             50.02   0.53           0.28
1263   89.60             89.91   0.31           0.10
3732   77.15             75.08   2.07           4.26
1672   72.10             70.10   2.00           4.01
811   104.00            104.96   0.96           0.92
2526   19.40             19.95   0.55           0.30
2892   20.45             19.95   0.50           0.25
4129   84.05             84.94   0.89           0.79
2622   51.00             50.03   0.97           0.95
3801   85.45             84.98   0.47           0.22
4357   20.45             19.95   0.50           0.25

Mean absolute error: 0.80

Root mean square error: 1.06

R-Squared: 0.99874

In [ ]:
#7 Compare to a Baseline (Single Variable Linear Regression)

addon_cols = ['phone_service', 'multiple_lines', 'online_security', 'online_backup', 'device_protection', 'tech_support', 'streaming_tv', 'streaming_movies', 'internet_fo', 'internet_no']
df = pd.DataFrame({'num_addons': dataset[addon_cols].sum(axis=1),   'monthly_charge': dataset['monthly_charges']})

X1 = df[["num_addons"]]
Y1 = df[["monthly_charge"]]

X_train1, X_test1, Y_train1, Y_test1 = train_test_split(X1, Y1, test_size = 0.15, random_state = 42)

print("X_train shape:", X_train1.shape)
print("X_test shape:", X_test1.shape)
print("Y_train shape:", Y_train1.shape)
print("Y_test shape:", Y_test1.shape)

model1=linear_model.LinearRegression()
model1.fit(X_train1,Y_train1)

coef = float(model1.coef_[0])
intb = float(model1.intercept_)


print()
print(f"Single Coefficient: {coef:.2f}")
print(f"Single Intercept: {intb:.2f}")
print(f"Linear Regression: {coef:.2f} * num_addons + {intb:.2f}")

Y1_prediction = model1.predict(X_test1)

results1 = X_test1.copy()
results1['actual'] = Y_test1.values
results1['model_prediction'] = Y1_prediction
results1['error'] = abs((results1['actual'] - results1['model_prediction']))
results1['error_squared'] = results1['error']**2
print(results1.round(2).head(15))
print()

mae = (1/len(Y_test1)) * results1['error'].sum()
rmse = np.sqrt((1/len(Y_test1)) * results1['error_squared'].sum())
r_2 = r2_score(Y_test1, Y1_prediction)
print(f"Mean absolute error: {mae:.2f}")
print()
print(f"Root mean square error: {rmse:.2f}")
print()
print(f"R-Squared: {r_2:.5f}")

X_train shape: (5986, 1)
X_test shape: (1057, 1)
Y_train shape: (5986, 1)
Y_test shape: (1057, 1)

Single Coefficient: 12.14
Single Intercept: 15.91
Linear Regression: 12.14 * num_addons + 15.91
      num_addons  actual  model_prediction  error  error_squared
185            0   24.80             15.91   8.89          79.02
2715           3   25.25             52.34  27.09         733.98
3825           2   19.35             40.20  20.85         434.65
1807           3   76.35             52.34  24.01         576.38
132            2   50.55             40.20  10.35         107.16
1263           5   89.60             76.63  12.97         168.23
3732           6   77.15             88.77  11.62         135.10
1672           6   72.10             88.77  16.67         278.00
811            7  104.00            100.92   3.08           9.51
2526           2   19.40             40.20  20.80         432.57
2892           2   20.45             40.20  19.75         389.99
4129           4   84.05             64.49  19.56         382.76
2622           2   51.00             40.20  10.80         116.68
3801           5   85.45             76.63   8.82          77.80
4357           2   20.45             40.20  19.75         389.99

Mean absolute error: 14.34

Root mean square error: 16.52

R-Squared: 0.69555

/tmp/ipykernel_5058/1944268227.py:19: DeprecationWarning: Conversion of an array with ndim > 0 to a scalar is deprecated, and will error in future. Ensure you extract a single element from your array before performing this operation. (Deprecated NumPy 1.25.)
  coef = float(model1.coef_[0])
/tmp/ipykernel_5058/1944268227.py:20: DeprecationWarning: Conversion of an array with ndim > 0 to a scalar is deprecated, and will error in future. Ensure you extract a single element from your array before performing this operation. (Deprecated NumPy 1.25.)
  intb = float(model1.intercept_)

In [ ]:
#8 Interpret the Results (Coefficients to USD)

print(linear_coefficients.round(2))
print()

for a in range(len(linear_coefficients)):
  print(f"Service {a+1}: {linear_coefficients['service'][a]} for ${linear_coefficients['$'][a].round(2)} per month.")

             service      $
8        internet_fo  24.94
0      phone_service  20.05
6       streaming_tv   9.98
7   streaming_movies   9.95
2    online_security   5.05
1     multiple_lines   5.02
5       tech_support   5.02
4  device_protection   5.01
3      online_backup   4.99
9        internet_no -25.06

Service 1: phone_service for $20.05 per month.
Service 2: multiple_lines for $5.02 per month.
Service 3: online_security for $5.05 per month.
Service 4: online_backup for $4.99 per month.
Service 5: device_protection for $5.01 per month.
Service 6: tech_support for $5.02 per month.
Service 7: streaming_tv for $9.98 per month.
Service 8: streaming_movies for $9.95 per month.
Service 9: internet_fo for $24.94 per month.
Service 10: internet_no for $-25.06 per month.

In [ ]:
#9 Make a Prediction (Input to Output)

#CHANGE to 1 for YES and 0 for NO

phone_service = 0
multiple_lines =
online_security = 0
online_backup = 0
device_protection = 0
tech_support = 0
streaming_tv =
streaming_movies = 0
internet_fo = 0
internet_no = 0

final_price_estimation = 24.95 + (20.05 * phone_service) + (5.02 * multiple_lines) + (5.05 * online_security) + (4.99 * online_backup) + (5.01 * device_protection) + (5.02 * tech_support) + (9.98 * streaming_tv) + (9.95 * streaming_movies) + (24.94 * internet_fo) + (-25.06 * internet_no)

print(f"Estimated monthly charge: ${final_price_estimation:.2f}")

Estimated monthly charge: $80.01